languageCode = "fa-ir"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "http://blog.khajavi.ir/"
canonifyurls = true
title = "یادداشتهای میلاد خواجوی"
author = "میلاد"
#disqusShortname = "khajavi" # Optional, enable Disqus integration
theme = "hyde-x"
MetaDataFormat = "toml"
paginate = 10

[indexes]
   category = "categories"
   tag = "tags"




[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    #post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = false

    # Used when a given page doesn't set its own.
    defaultDescription = "یادداشت‌های میلاد خواجوی"
    defaultKeywords = "دانش آزاد، نرم‌افزار آزاد"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08 layout-reverse"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    #highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "یادداشت‌های میلاد خواجوی"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "خانه"

    # Metadata used to drive integrations.
    #googleAuthorship = "Your Google+ profile ID"
    #googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "df11f04eba996eb3523af466fbdbeadb"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/khajavi/"
    bitbucket = ""
    stackOverflow = "http://stackoverflow.com/users/225052/milad-khajavi"
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/khajavi"
    youtube = ""
    email = "khajavi@gmail.com"
    description = "یک وبلاگ دیگر از یک برنامه نویس دیگر"


    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
    #flattr = ""  # populate with your flattr uid
